### ISSUE TITLE
mute-new-tabs does not unmute some players

### ISSUE THREAD

**Issue by ghost** [ludios/mute-new-tabs#8]
A video in this player can NOT be unmuted by clicking on the video's volume control.
When I clicked "Remove this extension" and removed mute-new-tab, the video's audio began to play at a normal and reasonable level.
While the video was playing, I reinstalled the extension.  The volume muted and no amount of clicking on the video's volume control would allow it to play.

SUGGESTION: ADD AN OPTION TO DISABLE mute-new-tabs FOR THIS TAB.
This would allow weird, new, non-compliant audio players to play even when mute-new-tabs doesn't know how to unmute them.

Brightcove Player Version | 5.22.4
-- | --
Video.js Version | 5.20.1
Account ID | 1509317113
Player ID | HJbWPHdb4b
Embed ID | default
Application ID

https://www.brightcove.com/en/

**Comment by ivan** [comment]
Thanks for the report. Mute New Tabs definitely doesn't support every player; the fallback option is to click the mute/unmute control on the tab.

Do you have a sample URL that uses this player? Maybe I can just add support for its volume control.

**Comment by ivan** [comment]
For my reference: the video on https://www.theverge.com/2015/12/8/9872746/apple-bad-hardware-design-iphone-case-pencil-magic-mouse uses Brightcove

**Comment by ivan** [comment]
One way to support unmute on video players more generically would be to wait for a click event on anything with "volume" or "mute" in the `class` or `id` in any of the 5 parent DOM elements in combination with a `volumechange` event on a `video` or `audio` tag.  There is a small risk of false positives, but if there are problems, the heuristics could be tweaked or a special blacklist could be added.

**Comment by ghost** [comment]
Mute unmute control on the tab didn't work either.
I figured it was decoration.

**Comment by ivan** [comment]
Yep, it's just decoration by default, unless "Tab audio muting UI control" is enabled in chrome://flags and Chrome restarted, at which point it should mute/unmute when clicked.

**Comment by ghost** [comment]
Ah. ok.  I didn't do that.

**Comment by ivan** [comment]
Closing because this project is archived and obsoleted by Chrome's native 'Mute site' / 'Unmute site'. Chrome now allows muting all sites by default.
