### ISSUE TITLE
Can't unmute tabs

### ISSUE THREAD

**Issue by dtJon** [ludios/mute-new-tabs#9]
<img width="312" alt="screen shot 2018-02-02 at 4 37 15 pm" src="https://user-images.githubusercontent.com/539584/35759563-971b9d18-0837-11e8-8600-9ca03ac4f422.png">

I am unable to un-mute tabs.  I don't see an option for "Unmute".  I am using Version 64.0.3282.119 (Official Build) (64-bit) on Mac OS X High Sierra.

**Comment by ivan** [comment]
Indeed, Chrome 64 unhelpfully removed "Mute tab" and "Unmute tab" from the context menu and now your only option (as far as I know) is to click on the little mute/unmute icon in the tab (which should be clickable if "Tab audio muting UI control" in enabled in chrome://flags).

**Comment by ivan** [comment]
I have found a solution (thanks to [this tweet](https://twitter.com/MegnaGaming/status/961124569607213058)):

chrome://flags -> Sound content setting -> **Disabled** and restart Chrome.

**Comment by ivan** [comment]
Closing because I updated the README with this information a while ago. Thanks for the report.
